### ISSUE TITLE
Error when adding Video Editing Tab

### ISSUE THREAD

**Issue by j2l** [ubisoft/shotmanager#29]
**Infos on the context**
- Add-on version: 2.0.102
- Blender version, from installer or from zip: 2.93.3
- OS: Ubuntu 21.10
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): IDK

**Describe the bug**
Error panel popping out when adding the Video Editing tab in Blender.
```
-------------------------------------------------------

New file loaded

Initializing Shot Manager in the current scene (Scene)...                                                                                    [./config/sm_logging.py:222]

Initializing Shot Manager Preferences...

Initializing new take with name Main Take...

REFRESH JIGGLE LIST
anim drop
Python: [ERROR] mpfb.init ..............................: Unhandled crash 
  File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:

local variable 'event_handled' referenced before assignment

Traceback (most recent call last):
  File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:
UnboundLocalError: local variable 'event_handled' referenced before assignment

location: <unknown location>:-1
Error: Python: [ERROR] mpfb.init ..............................: Unhandled crash 
  File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:

local variable 'event_handled' referenced before assignment

Traceback (most recent call last):
  File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:
UnboundLocalError: local variable 'event_handled' referenced before assignment

location: <unknown location>:-1

```

**To Reproduce**

**Expected behavior**
no error :smile: 

**Screenshots**
![Screenshot from 2022-06-22 10-01-56](https://user-images.githubusercontent.com/65325/174977376-e0cee21f-ace9-4f0c-a295-55ae375a4235.png)

**Comment by werwack** [comment]
Can you check with this version please? I believe it is the same issue than the other one you repported:
[V2.0.225](https://github.com/ubisoft/shotmanager/releases)
