### ISSUE TITLE
local variable 'event_handled' referenced before assignment

### ISSUE THREAD

**Issue by j2l** [ubisoft/shotmanager#30]
**Infos on the context**
- Add-on version: beta 2
- Blender version, from installer or from zip: 2.93.3
- OS: ubuntu
- 
**Describe the bug**
adding mkv file to video editor crashed blender:
```
 File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:

local variable 'event_handled' referenced before assignment

Traceback (most recent call last):
  File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:
UnboundLocalError: local variable 'event_handled' referenced before assignment

location: <unknown location>:-1
Error: Python: [ERROR] mpfb.init ..............................: Unhandled crash 
  File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:

local variable 'event_handled' referenced before assignment

Traceback (most recent call last):
  File "/home/pm/.config/blender/2.93/scripts/addons/shotmanager/overlay_tools/interact_shots_stack/shots_stack.py", line 248, in modal
    if config.gRedrawShotStack or event_handled:
UnboundLocalError: local variable 'event_handled' referenced before assignment

location: <unknown location>:-1


drop file /home/pm/Documents/sower_rue.mkv
Couldn't open indexer file: /home/pm/Documents/BL_proxy/sower_rue.mkv/record_run.blen_tc
Starting work on proxy: /home/pm/Documents/BL_proxy/sower_rue.mkv/proxy_100_part.avi
Starting work on index: /home/pm/Documents/BL_proxy/sower_rue.mkv/record_run.blen_tc
Starting work on index: /home/pm/Documents/BL_proxy/sower_rue.mkv/free_run.blen_tc
Starting work on index: /home/pm/Documents/BL_proxy/sower_rue.mkv/interp_free_run.blen_tc
Starting work on index: /home/pm/Documents/BL_proxy/sower_rue.mkv/record_run_no_gaps.blen_tc
Writing: /tmp/blender.crash.txt
Segmentation fault (core dumped)
```

**Comment by werwack** [comment]
That's a weird bug... 😲
Looking at the code I can't see how the message "local variable 'event_handled' referenced before assignment" can appear...
Can you confirm me your are well on 2.0.102 here?
thank you

**Comment by j2l** [comment]
yes

**Comment by werwack** [comment]
Hi @j2l ,
I did a fix on the latest release, let me know if it works.
Cf [V2.0.225](https://github.com/ubisoft/shotmanager/releases)
